#include <stdio.h>
#include <string.h>

static void trim_newline(char *value) {
    value[strcspn(value, "\n")] = '\0';
}

static void print_escaped(const char *value) {
    for (const char *cursor = value; *cursor != '\0'; cursor++) {
        switch (*cursor) {
            case '&':
                printf("&amp;");
                break;
            case '<':
                printf("&lt;");
                break;
            case '>':
                printf("&gt;");
                break;
            case '"':
                printf("&quot;");
                break;
            case '\'':
                printf("&#39;");
                break;
            default:
                putchar(*cursor);
        }
    }
}

int main(void) {
    char alias[100];
    char secretCode[100];
    char level[20];

    printf("SweatSync legacy HTML generator demo\n");
    printf("Enter your gym alias: ");
    fgets(alias, sizeof(alias), stdin);
    trim_newline(alias);

    printf("Enter your demo access code: ");
    fgets(secretCode, sizeof(secretCode), stdin);
    trim_newline(secretCode);

    printf("Select gym level (casual/regular/dedicated/obsessed): ");
    fgets(level, sizeof(level), stdin);
    trim_newline(level);

    printf("<!DOCTYPE html>\n");
    printf("<html lang=\"en\">\n");
    printf("<head>\n");
    printf("    <meta charset=\"UTF-8\">\n");
    printf("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
    printf("    <title>SweatSync Legacy Result</title>\n");
    printf("    <link rel=\"stylesheet\" href=\"style.css\">\n");
    printf("</head>\n");
    printf("<body>\n");
    printf("    <main class=\"app-shell auth-shell\">\n");
    printf("        <section class=\"auth-panel\">\n");
    printf("            <p class=\"eyebrow\">Legacy demo</p>\n");
    printf("            <h1>SweatSync Result</h1>\n");
    printf("            <p>Hello ");
    print_escaped(alias);
    printf(". This static HTML was generated by the legacy C demo.</p>\n");

    if (strcmp(level, "dedicated") == 0 || strcmp(level, "obsessed") == 0) {
        printf("            <div class=\"result-panel\">\n");
        printf("                <h2>Premium preview</h2>\n");
        printf("                <p>Your selected level qualifies for the mock premium dashboard.</p>\n");
        printf("                <a class=\"primary-action compact-action\" href=\"premium-matches.html\">Open dashboard</a>\n");
        printf("            </div>\n");
    } else {
        printf("            <div class=\"result-panel\">\n");
        printf("                <h2>Demo upgrade path</h2>\n");
        printf("                <p>This mock would offer coaching and profile-building prompts before opening premium matches.</p>\n");
        printf("                <a class=\"primary-action compact-action\" href=\"premium-matches.html\">Preview dashboard</a>\n");
        printf("            </div>\n");
    }

    printf("        </section>\n");
    printf("    </main>\n");
    printf("</body>\n");
    printf("</html>\n");

    return 0;
}
